### ISSUE TITLE
Noobish question..

### ISSUE THREAD

**Issue by SuperJojo2001** [biancode/node-modbus-1#2]
biancode, when I install "node-modbus" today under my windows system with command "npm installl node-modbus", then I see the npm pulling the version 2.1.1 which is the latest release under npm, which is fine.

But why is this installation still pulling an old "modbus-serial-client.js" file with this content in line 127

if(this.endianType === 'BIG') {
                pktWithCRC = pkt.word16be(crc.crc16modbus(buf)).buffer();
            }
            else {
                pktWithCRC = pkt.word16le(crc.crc16modbus(buf)).buffer();
            }

The new source code modbus-serial-client.js I see here shows me the correct coding.

 var pktWithCRC = pkt.word16le(crc.crc16modbus(buf)).buffer();

Thx

**Comment by biancode** [comment]
It wasn't released - I had to do some testing for that release  -  please test v0.9.1 with node-modbus 2.1.2
